######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 22 21:31:34 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=opengl

# Input
SOURCES += cg_main.cpp
